/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const json_to_typescript: (a: number, b: number) => [number, number, number, number];
export const json_to_java: (a: number, b: number) => [number, number, number, number];
export const json_to_golang: (a: number, b: number) => [number, number, number, number];
export const json_to_python: (a: number, b: number) => [number, number, number, number];
export const yaml_to_typescript: (a: number, b: number) => [number, number, number, number];
export const yaml_to_java: (a: number, b: number) => [number, number, number, number];
export const yaml_to_python: (a: number, b: number) => [number, number, number, number];
export const yaml_to_golang: (a: number, b: number) => [number, number, number, number];
export const xml_to_typescript: (a: number, b: number) => [number, number, number, number];
export const xml_to_java: (a: number, b: number) => [number, number, number, number];
export const xml_to_golang: (a: number, b: number) => [number, number, number, number];
export const xml_to_python: (a: number, b: number) => [number, number, number, number];
export const csv_to_typescript: (a: number, b: number) => [number, number, number, number];
export const csv_to_java: (a: number, b: number) => [number, number, number, number];
export const csv_to_golang: (a: number, b: number) => [number, number, number, number];
export const csv_to_python: (a: number, b: number) => [number, number, number, number];
export const json_to_json_schema: (a: number, b: number) => [number, number, number, number];
export const json_to_yaml: (a: number, b: number) => [number, number, number, number];
export const json_to_xml: (a: number, b: number) => [number, number, number, number];
export const json_to_csv: (a: number, b: number) => [number, number, number, number];
export const yaml_to_json: (a: number, b: number) => [number, number, number, number];
export const yaml_to_xml: (a: number, b: number) => [number, number, number, number];
export const yaml_to_csv: (a: number, b: number) => [number, number, number, number];
export const xml_to_json: (a: number, b: number) => [number, number, number, number];
export const xml_to_yaml: (a: number, b: number) => [number, number, number, number];
export const xml_to_csv: (a: number, b: number) => [number, number, number, number];
export const csv_to_json: (a: number, b: number) => [number, number, number, number];
export const csv_to_yaml: (a: number, b: number) => [number, number, number, number];
export const csv_to_xml: (a: number, b: number) => [number, number, number, number];
export const process_json_tree: (a: number, b: number) => [number, number, number, number];
export const process_json: (a: number, b: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
